  alias: All lights ON - Fire/Alarm
  initial_state: true
  trigger:
  - entity_id: sensor.larm_status
    platform: state
    to: 'Alarm'
  - entity_id: sensor.larm_status
    platform: state
    to: 'Fire'
  action:
  - data:
      brightness: 255
      entity_id: group.all_lights
    service: light.turn_on
