## your file here ###

- platform: rest
  scan_interval: 1
  name: Selfmon
  json_attributes:
    - status
    - xtra
    - usr
  resource: http:// <your_web_server> /status/selfmon.json
  value_template: '{{ value_json.status }}'

- platform: template
  sensors:
    larm_status:
      value_template: >
        {{ states.sensor.selfmon.attributes.status }}
    larm_last_changed:
      value_template: >
        {{ states.sensor.selfmon.attributes.xtra }}
    larm_last_users:
      value_template: >
        {{ states.sensor.selfmon.attributes.usr }}

rest_command:
  vkp_command:
    url: 'http:// <your_vkp_java_server:port> /KP.xml?u={{ rnd }}&web1={{ cmd }}&counter={{ cnt }}'

## your file here ###
